try{
    console.log(apenasUmTeste)
}catch(erro){
    console.log("apenasUmTeste n√£o existe")
} 